### ISSUE TITLE
Detail view does not find the instance when using the hashed id

### ISSUE THREAD

**Issue by OskarPersson** [evenicoulddoit/django-rest-framework-serializer-extensions#12]
With the app below I can visit localhost/api/books and I see the id and url correctly hashed for each book. But if I visit the url for a book I get a 404. Switching out the hashed id with the raw id in the url shows the correct book.

*I'm using Django 1.11.3 and Django Rest Framework 3.6.3 on Python 3.6.0*

```
# settings.py

REST_FRAMEWORK = {
    'SERIALIZER_EXTENSIONS': {
        'USE_HASH_IDS': True,
        'HASH_IDS_SOURCE': 'books.HASH_IDS'
    }
}
```

```
# books/__init__.py

import hashids
HASH_IDS = hashids.Hashids(salt='MYSALT')
```

```
# books/models.py

class Book(models.Model):
    id = models.AutoField(primary_key=True)
```

```
# books/serializers.py

class BookSerializer(serializers.HyperlinkedModelSerializer):
    url = HashIdHyperlinkedIdentityField(model=Book, view_name='book-detail')
    id = HashIdField(model=Book)
```

```
# urls.py

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'books', BookViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
]
```

**Comment by evenicoulddoit** [comment]
Hi Oskar, thanks for this. You seem to have omitted your Viewset.

I've not actually got any experience with using Rest Framework's router. I'm happy to take a look at how to integrate routers with extensions when I get some free time, but in the meantime you might want to look at the [`ExternalIdViewMixin`](https://github.com/evenicoulddoit/django-rest-framework-serializer-extensions/blob/master/rest_framework_serializer_extensions/views.py#L59) and see if you can add it to your ViewSets.

Hope that helps, will come back to you with more if not when I get the chance

**Comment by OskarPersson** [comment]
Including [`ExternalIdViewMixin`](https://github.com/evenicoulddoit/django-rest-framework-serializer-extensions/blob/master/rest_framework_serializer_extensions/views.py#L59) solved it for `rest_framework.viewsets.ModelViewSet` but not for `django.views.generic.DetailView`

```
class BookViewSet(ExternalIdViewMixin, viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
```

```
class BookDetailView(ExternalIdViewMixin, generic.DetailView):
    model = Book
    template_name = 'books/book.html'
    context_object_name = "book"
```

The `BookDetailView` raises

```
AttributeError: 'BookDetailView' object has no attribute 'filter
_queryset'
```

Deleting the `ExternalIdViewMixin` from `BookDetailView`raises

```
ValueError: invalid literal for int() with base 10: 'V3CM'
```

**Comment by evenicoulddoit** [comment]
It seems like you're mixing concerns here, where the viewset is Django Rest Framework and the DetailView is Django?

**Comment by OskarPersson** [comment]
Yes, DetailView is Django and viewset is DRF, but I need both to use HashID. Though maybe this is the wrong place for discussing DetailView. Viewsets are fixed so I'm closing this.
