### ISSUE TITLE
util.import_local fails on apps with compound paths

### ISSUE THREAD

**Issue by mhotwagner** [evenicoulddoit/django-rest-framework-serializer-extensions#13]
The local import utility handles apps with simple paths (no-dot), but fails on apps with compound paths (ie, dots).   So, this works fine:
```
INSTALLED_APPS = ('some_app',)
import_local('some_app.SomeClass')
```

But this fails:
```
INSTALLED_APPS = ('some_top_level_package.some_module')
import_local('some_top_level_package.some_module.SomeClass')
```

The issue lies here, in the import_local function:
```
def import_local(path_to_object)
    path, name = path_to_object.rsplit('.', 1)

    app = path.split('.')[0]  # Assumes the app is the 0th element of the path

    if app not in settings.INSTALLED_APPS:
        raise AssertionError()
```

Restricting possible app names to the 0th element of the path means we ignore apps with compound paths. Solution should check `INSTALLED_APPS` for all iterations of the path.

**Comment by evenicoulddoit** [comment]
@mhotwagner Thanks for your patience - new version just pushed out with your changes in :)
