### ISSUE TITLE
Documentation for HashIds should mention the use of the ExternalIdViewMixin

### ISSUE THREAD

**Issue by joeribekker** [evenicoulddoit/django-rest-framework-serializer-extensions#18]
Without `ExternalIdViewMixin` in your `APIView`, the detail views don't work with the hashed IDs. This should be mentioned in your documentation.

Reading your unit tests was the only way I found out. Then again, it's unit tested 👍

**Comment by evenicoulddoit** [comment]
Good point! Will add something now
