### ISSUE TITLE
Name the result array

### ISSUE THREAD

**Issue by noelvillaman** [evenicoulddoit/django-rest-framework-serializer-extensions#23]
Is there a way to give a name to you Json array? Or what would be the name of the array?

**Comment by evenicoulddoit** [comment]
I'm sorry but I have no idea what you mean. Could you please elaborate?

**Comment by noelvillaman** [comment]
["glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to
create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}The example above shows that "glossary" is the name of this array. Is
there a way to add a name like this?


noel.

**Comment by evenicoulddoit** [comment]
That's not how Arrays work

**Comment by noelvillaman** [comment]
Yes, it is. They do have a name. Copy and past your result array to
myjson.com and you will get an error. Your project is missing that.

**Comment by evenicoulddoit** [comment]
https://jsonformatter.org/c76368
