### ISSUE TITLE
DRF 3.9+ compatbility

### ISSUE THREAD

**Issue by antwan** [evenicoulddoit/django-rest-framework-serializer-extensions#26]
DRF 3.9 introduced an [argument renaming](https://github.com/encode/django-rest-framework/pull/5990) in the routers.

DRFE needs to adapt its routers to support the future versions. It will break after 3.10 as per deprecation plan.

**Comment by evenicoulddoit** [comment]
Hi @antwan. Thanks for reporting this. I'm no longer working with DRF so I've been out of the loop for a while. Would happily accept PRs to get this sorted if its trivial. Otherwise I'll see if I can get the time to look into it, but not sure when that'll be

**Comment by evenicoulddoit** [comment]
Hi @antwan, I've just bumped the package versions, and looked at the link you sent, but can't see anything within this project's code which is relevant to the link you sent. That is to say I don't make use of `basename`. I'm going to close this issue, DRF 3.9 compatibility appears fine, but let me know if you think I've missed something.

**Comment by antwan** [comment]
My bad it was for `drf-extensions`. Thanks for the update though.
