### ISSUE TITLE
Only/Exclude mixins result in fields as a Dictionary not an OrderedDict

### ISSUE THREAD

**Issue by evenicoulddoit** [evenicoulddoit/django-rest-framework-serializer-extensions#3]
Found this out during another bug, but it seems reasonable that reducing the fields for a serializer should retain the original ordering

**Comment by joeribekker** [comment]
Just a heads up to others encountering this problem and only using the "expandable" behaviour. If you extend your `Serializer` with the `rest_framework_serializer_extensions.serializers.ExpandableFieldsMixin` (which is also used in the `SerializerExtensionsMixin`), ordering is retained while getting the "expandable" behaviour.
