### ISSUE TITLE
This just doesn't work

### ISSUE THREAD

**Issue by michealjroberts** [evenicoulddoit/django-rest-framework-serializer-extensions#40]
I've followed all of the reproducable steps in the documentation, and my fields are now excluded:

```
class DomainSerializer(
    SerializerExtensionsMixin,
    serializers.ModelSerializer
):
    # disciplines = BranchSerializer(many=True)

    # dataset_count = serializers.SerializerMethodField()

    class Meta:
        model = Domain
        fields = [
            'uuid', 'id', 'name', 'slug', 'thumbnail',
        ]
        expandable_fields = dict(
            dataset_count=serializers.SerializerMethodField,
            disciplines=dict(
                serializer=BranchSerializer,
                many=True
            )
        )


    def get_dataset_count(self, obj):
        return obj.datasets.all().count()
```

And now in the listing API viewset:

```
class DomainViewset(
    SerializerExtensionsAPIViewMixin,
    ListAPIView
):
    queryset = Domain.objects.all()
    serializer_class = DomainSerializer
    extensions_auto_optimize = True
```

When hitting the endpoint, it lists, minus the expandable fields.

What am I doing wrong? What can I do to help improve the documentation?

**Comment by evenicoulddoit** [comment]
What do you mean it doesn't work? When you hit the endpoint it _shouldn't_ do anything by default given the above. Could you be more specific. Also, what have you tried?

**Comment by michealjroberts** [comment]
@evenicoulddoit So how to we use it then? I've followed the example and replicated the steps as closely as possible, no errors thrown, it just lists the Domain models, minus the two fields I have tried to work with the `expandable_fields` value in the Serialzier...

**Comment by evenicoulddoit** [comment]
Hi @michealjroberts - I'm going to close this for now and point you towards the [examples](https://github.com/evenicoulddoit/django-rest-framework-serializer-extensions#examples) in the README. The [full documentation](https://django-rest-framework-serializer-extensions.readthedocs.io/en/latest/) may also help. If you have a specific issue, please let me know.
