### ISSUE TITLE
how to deal with _id_resolved

### ISSUE THREAD

**Issue by arnoldordz** [evenicoulddoit/django-rest-framework-serializer-extensions#44]
Request Method: | POST
-- | --
http://localhost:8000/api/customers/
3.1.3
TypeError
Customer() got an unexpected keyword argument 'condition_id_resolved'
/data/python/PycharmProjects/_brainapi/venv/lib/python3.7/site-packages/django/db/models/base.py, line 501, in __init__
/data/python/PycharmProjects/_brainapi/venv/bin/python
3.7.9
['/data/python/PycharmProjects/_brainapi',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/data/python/PycharmProjects/_brainapi/venv/lib/python3.7/site-packages']
Wed, 11 Nov 2020 23:07:51 +0000

**Comment by evenicoulddoit** [comment]
Hi @arnoldordz - please read this section - https://github.com/evenicoulddoit/django-rest-framework-serializer-extensions/blob/b66500af5e1cfc23d72049548145ae762cbc289f/docs/usage-serializers.md#writable-foreignkey-relationships

I don't think this is a bug, you just need to decide what you want to do.
