### ISSUE TITLE
Unable to access related object specified in expandable_fields from serializer

### ISSUE THREAD

**Issue by rldiao** [evenicoulddoit/django-rest-framework-serializer-extensions#45]
Hi,

I'm currently using this library with DRF 3.12  and trying to perform some validations in the serializer by checking a related object.

Something like this:
```python
class FooSerializer(SerializerExtensionsMixin, serializers.ModelSerializer):
    class Meta:
        model = Foo
        expandable_fields = dict(
          bar=BarSerializer,
        )

   def validate(self, data):
        try:
            # For POST
            bar = data['Bar']
        expect KeyError:
            # For PATCH
            bar = self.instance.bar
        if bar.time < datetime.now():
            raise ValidationError()
        return data
```
This code works when `Bar` is specified in `fields` but not `expandable_field`. Just asking if the object is stored somewhere where I can assess?

Thanks

**Comment by evenicoulddoit** [comment]
Hey! I'm just trying to understand the use case, but also looking at the code sample I see the Bar is title-cased in one instance. Am I just to assume that this is a typo in your example, and not the cause of your problem?

**Comment by rldiao** [comment]
Yeah that would just be a typo. I'm basically trying validate if you can create or update the object based on a related object's field. 

So in the case of you trying to change `foo` but `now()` is greater than `bar.time`, then `validate` will raise a `ValidationError`

**Comment by evenicoulddoit** [comment]
And have you seen the [writable foreign keys section](https://django-rest-framework-serializer-extensions.readthedocs.io/en/latest/usage-serializers/), here?

**Comment by rldiao** [comment]
After some thought, I've decided to pursue a different solution to my problem. Thanks for the support
