### ISSUE TITLE
Add formal support for Django 1.11

### ISSUE THREAD

**Issue by evenicoulddoit** [evenicoulddoit/django-rest-framework-serializer-extensions#6]
* Upgrade versions checked using tox to 1.11
* Drop support for 1.8

**Comment by mattaustin** [comment]
Django 1.8 LTS is still supported for another year, so I would kindly ask that support isn't dropped at this time (rest framework will also continue support).

Django 1.9 (non-LTS) support ended when Django 1.11 LTS was released, so Django 1.9 support can be dropped.

Thanks.

**Comment by evenicoulddoit** [comment]
Great point @mattaustin - I was working on the assumption of supporting "current - 2" releases, but should probably look at the DSFs suggestions and be consistent (i.e. respect LTS releases)

**Comment by KyeRussell** [comment]
Any updates on this?

**Comment by evenicoulddoit** [comment]
@KyeRussell good question! Looks like I've already done the work in another branch which I've been on the fence as to whether to push or not. I'll just cherry pick that work and make a release, though I suppose I should also spend a little time adding support for Django 2 - I think I might need to have some conditional imports in order to do so. Will look at it ASAP!

**Comment by evenicoulddoit** [comment]
@KyeRussell  this is now done, thanks for the nudge.

In line with Django, support is now 1.8/1.11/2.0
